/* C glX bindings generated by glbindify 0.5.1 */
/* Command line: glbindify -n glplatform -a glx */

#ifndef GL_BINDIFY_glx_H
#define GL_BINDIFY_glx_H
#ifdef __cplusplus
extern "C" {
#endif
#include <X11/Xlib.h>
#include <X11/Xutil.h>
#include <stdint.h>
#include <stddef.h>
#include <string.h>
#include <stdbool.h>
#ifndef GLBINDIFY_COMMON_GL_TYPEDEFS
#define GLBINDIFY_COMMON_GL_TYPEDEFS
typedef unsigned int GLenum;
typedef unsigned char GLboolean;
typedef unsigned int GLbitfield;
typedef signed char GLbyte;
typedef short GLshort;
typedef int GLint;
typedef unsigned char GLubyte;
typedef unsigned short GLushort;
typedef unsigned int GLuint;
typedef int GLsizei;
typedef float GLfloat;
typedef double GLdouble;
typedef ptrdiff_t GLintptr;
typedef ptrdiff_t GLsizeiptr;
#endif
#ifndef GLPLATFORM_GLX_VERSION
#define GLPLATFORM_GLX_VERSION 14
#endif
typedef XID GLXFBConfigID;
typedef struct __GLXFBConfigRec *GLXFBConfig;
typedef XID GLXContextID;
typedef struct __GLXcontextRec *GLXContext;
typedef XID GLXPixmap;
typedef XID GLXDrawable;
typedef XID GLXWindow;
typedef XID GLXPbuffer;
typedef void ( *__GLXextFuncPtr)(void);
typedef XID GLXVideoCaptureDeviceNV;
typedef unsigned int GLXVideoDeviceNV;
typedef XID GLXVideoSourceSGIX;
typedef XID GLXFBConfigIDSGIX;
typedef struct __GLXFBConfigRec *GLXFBConfigSGIX;
typedef XID GLXPbufferSGIX;
typedef struct {
    int event_type;             /* GLX_DAMAGED or GLX_SAVED */
    int draw_type;              /* GLX_WINDOW or GLX_PBUFFER */
    unsigned long serial;       /* # of last request processed by server */
    Bool send_event;            /* true if this came for SendEvent request */
    Display *display;           /* display the event was read from */
    GLXDrawable drawable;       /* XID of Drawable */
    unsigned int buffer_mask;   /* mask indicating which buffers are affected */
    unsigned int aux_buffer;    /* which aux buffer was affected */
    int x, y;
    int width, height;
    int count;                  /* if nonzero, at least this many more */
} GLXPbufferClobberEvent;
typedef struct {
    int type;
    unsigned long serial;       /* # of last request processed by server */
    Bool send_event;            /* true if this came from a SendEvent request */
    Display *display;           /* Display the event was read from */
    GLXDrawable drawable;       /* drawable on which event was requested in event mask */
    int event_type;
    int64_t ust;
    int64_t msc;
    int64_t sbc;
} GLXBufferSwapComplete;
typedef union __GLXEvent {
    GLXPbufferClobberEvent glxpbufferclobber;
    GLXBufferSwapComplete glxbufferswapcomplete;
    long pad[24];
} GLXEvent;
typedef struct {
    int type;
    unsigned long serial;
    Bool send_event;
    Display *display;
    int extension;
    int evtype;
    GLXDrawable window;
    Bool stereo_tree;
} GLXStereoNotifyEventEXT;
typedef struct {
    int type;
    unsigned long serial;   /* # of last request processed by server */
    Bool send_event;        /* true if this came for SendEvent request */
    Display *display;       /* display the event was read from */
    GLXDrawable drawable;   /* i.d. of Drawable */
    int event_type;         /* GLX_DAMAGED_SGIX or GLX_SAVED_SGIX */
    int draw_type;          /* GLX_WINDOW_SGIX or GLX_PBUFFER_SGIX */
    unsigned int mask;      /* mask indicating which buffers are affected*/
    int x, y;
    int width, height;
    int count;              /* if nonzero, at least this many more */
} GLXBufferClobberEventSGIX;
typedef struct {
    char    pipeName[80]; /* Should be [GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX] */
    int     networkId;
} GLXHyperpipeNetworkSGIX;
typedef struct {
    char    pipeName[80]; /* Should be [GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX] */
    int     channel;
    unsigned int participationType;
    int     timeSlice;
} GLXHyperpipeConfigSGIX;
typedef struct {
    char pipeName[80]; /* Should be [GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX] */
    int srcXOrigin, srcYOrigin, srcWidth, srcHeight;
    int destXOrigin, destYOrigin, destWidth, destHeight;
} GLXPipeRect;
typedef struct {
    char pipeName[80]; /* Should be [GLX_HYPERPIPE_PIPE_NAME_LENGTH_SGIX] */
    int XOrigin, YOrigin, maxHeight, maxWidth;
} GLXPipeRectLimits;
#undef GLX_ACCUM_ALPHA_SIZE
#define GLX_ACCUM_ALPHA_SIZE 0x11
#undef GLX_ACCUM_BLUE_SIZE
#define GLX_ACCUM_BLUE_SIZE 0x10
#undef GLX_ACCUM_BUFFER_BIT
#define GLX_ACCUM_BUFFER_BIT 0x80
#undef GLX_ACCUM_GREEN_SIZE
#define GLX_ACCUM_GREEN_SIZE 0xf
#undef GLX_ACCUM_RED_SIZE
#define GLX_ACCUM_RED_SIZE 0xe
#undef GLX_ALPHA_SIZE
#define GLX_ALPHA_SIZE 0xb
#undef GLX_AUX_BUFFERS
#define GLX_AUX_BUFFERS 0x7
#undef GLX_AUX_BUFFERS_BIT
#define GLX_AUX_BUFFERS_BIT 0x10
#undef GLX_BACK_LEFT_BUFFER_BIT
#define GLX_BACK_LEFT_BUFFER_BIT 0x4
#undef GLX_BACK_RIGHT_BUFFER_BIT
#define GLX_BACK_RIGHT_BUFFER_BIT 0x8
#undef GLX_BAD_ATTRIBUTE
#define GLX_BAD_ATTRIBUTE 0x2
#undef GLX_BAD_CONTEXT
#define GLX_BAD_CONTEXT 0x5
#undef GLX_BAD_ENUM
#define GLX_BAD_ENUM 0x7
#undef GLX_BAD_SCREEN
#define GLX_BAD_SCREEN 0x1
#undef GLX_BAD_VALUE
#define GLX_BAD_VALUE 0x6
#undef GLX_BAD_VISUAL
#define GLX_BAD_VISUAL 0x4
#undef GLX_BLUE_SIZE
#define GLX_BLUE_SIZE 0xa
#undef GLX_BUFFER_SIZE
#define GLX_BUFFER_SIZE 0x2
#undef GLX_BufferSwapComplete
#define GLX_BufferSwapComplete 0x1
#undef GLX_COLOR_INDEX_BIT
#define GLX_COLOR_INDEX_BIT 0x2
#undef GLX_COLOR_INDEX_TYPE
#define GLX_COLOR_INDEX_TYPE 0x8015
#undef GLX_CONFIG_CAVEAT
#define GLX_CONFIG_CAVEAT 0x20
#undef GLX_DAMAGED
#define GLX_DAMAGED 0x8020
#undef GLX_DEPTH_BUFFER_BIT
#define GLX_DEPTH_BUFFER_BIT 0x20
#undef GLX_DEPTH_SIZE
#define GLX_DEPTH_SIZE 0xc
#undef GLX_DIRECT_COLOR
#define GLX_DIRECT_COLOR 0x8003
#undef GLX_DONT_CARE
#define GLX_DONT_CARE 0xffffffff
#undef GLX_DOUBLEBUFFER
#define GLX_DOUBLEBUFFER 0x5
#undef GLX_DRAWABLE_TYPE
#define GLX_DRAWABLE_TYPE 0x8010
#undef GLX_EVENT_MASK
#define GLX_EVENT_MASK 0x801f
#undef GLX_EXTENSIONS
#define GLX_EXTENSIONS 0x3
#undef GLX_EXTENSION_NAME
#define GLX_EXTENSION_NAME "GLX"
#undef GLX_FBCONFIG_ID
#define GLX_FBCONFIG_ID 0x8013
#undef GLX_FRONT_LEFT_BUFFER_BIT
#define GLX_FRONT_LEFT_BUFFER_BIT 0x1
#undef GLX_FRONT_RIGHT_BUFFER_BIT
#define GLX_FRONT_RIGHT_BUFFER_BIT 0x2
#undef GLX_GRAY_SCALE
#define GLX_GRAY_SCALE 0x8006
#undef GLX_GREEN_SIZE
#define GLX_GREEN_SIZE 0x9
#undef GLX_HEIGHT
#define GLX_HEIGHT 0x801e
#undef GLX_LARGEST_PBUFFER
#define GLX_LARGEST_PBUFFER 0x801c
#undef GLX_LEVEL
#define GLX_LEVEL 0x3
#undef GLX_MAX_PBUFFER_HEIGHT
#define GLX_MAX_PBUFFER_HEIGHT 0x8017
#undef GLX_MAX_PBUFFER_PIXELS
#define GLX_MAX_PBUFFER_PIXELS 0x8018
#undef GLX_MAX_PBUFFER_WIDTH
#define GLX_MAX_PBUFFER_WIDTH 0x8016
#undef GLX_NONE
#define GLX_NONE 0x8000
#undef GLX_NON_CONFORMANT_CONFIG
#define GLX_NON_CONFORMANT_CONFIG 0x800d
#undef GLX_NO_EXTENSION
#define GLX_NO_EXTENSION 0x3
#undef GLX_PBUFFER
#define GLX_PBUFFER 0x8023
#undef GLX_PBUFFER_BIT
#define GLX_PBUFFER_BIT 0x4
#undef GLX_PBUFFER_CLOBBER_MASK
#define GLX_PBUFFER_CLOBBER_MASK 0x8000000
#undef GLX_PBUFFER_HEIGHT
#define GLX_PBUFFER_HEIGHT 0x8040
#undef GLX_PBUFFER_WIDTH
#define GLX_PBUFFER_WIDTH 0x8041
#undef GLX_PIXMAP_BIT
#define GLX_PIXMAP_BIT 0x2
#undef GLX_PRESERVED_CONTENTS
#define GLX_PRESERVED_CONTENTS 0x801b
#undef GLX_PSEUDO_COLOR
#define GLX_PSEUDO_COLOR 0x8004
#undef GLX_PbufferClobber
#define GLX_PbufferClobber 0x0
#undef GLX_RED_SIZE
#define GLX_RED_SIZE 0x8
#undef GLX_RENDER_TYPE
#define GLX_RENDER_TYPE 0x8011
#undef GLX_RGBA
#define GLX_RGBA 0x4
#undef GLX_RGBA_BIT
#define GLX_RGBA_BIT 0x1
#undef GLX_RGBA_TYPE
#define GLX_RGBA_TYPE 0x8014
#undef GLX_SAMPLES
#define GLX_SAMPLES 0x186a1
#undef GLX_SAMPLE_BUFFERS
#define GLX_SAMPLE_BUFFERS 0x186a0
#undef GLX_SAVED
#define GLX_SAVED 0x8021
#undef GLX_SCREEN
#define GLX_SCREEN 0x800c
#undef GLX_SLOW_CONFIG
#define GLX_SLOW_CONFIG 0x8001
#undef GLX_STATIC_COLOR
#define GLX_STATIC_COLOR 0x8005
#undef GLX_STATIC_GRAY
#define GLX_STATIC_GRAY 0x8007
#undef GLX_STENCIL_BUFFER_BIT
#define GLX_STENCIL_BUFFER_BIT 0x40
#undef GLX_STENCIL_SIZE
#define GLX_STENCIL_SIZE 0xd
#undef GLX_STEREO
#define GLX_STEREO 0x6
#undef GLX_TRANSPARENT_ALPHA_VALUE
#define GLX_TRANSPARENT_ALPHA_VALUE 0x28
#undef GLX_TRANSPARENT_BLUE_VALUE
#define GLX_TRANSPARENT_BLUE_VALUE 0x27
#undef GLX_TRANSPARENT_GREEN_VALUE
#define GLX_TRANSPARENT_GREEN_VALUE 0x26
#undef GLX_TRANSPARENT_INDEX
#define GLX_TRANSPARENT_INDEX 0x8009
#undef GLX_TRANSPARENT_INDEX_VALUE
#define GLX_TRANSPARENT_INDEX_VALUE 0x24
#undef GLX_TRANSPARENT_RED_VALUE
#define GLX_TRANSPARENT_RED_VALUE 0x25
#undef GLX_TRANSPARENT_RGB
#define GLX_TRANSPARENT_RGB 0x8008
#undef GLX_TRANSPARENT_TYPE
#define GLX_TRANSPARENT_TYPE 0x23
#undef GLX_TRUE_COLOR
#define GLX_TRUE_COLOR 0x8002
#undef GLX_USE_GL
#define GLX_USE_GL 0x1
#undef GLX_VENDOR
#define GLX_VENDOR 0x1
#undef GLX_VERSION
#define GLX_VERSION 0x2
#undef GLX_VISUAL_ID
#define GLX_VISUAL_ID 0x800b
#undef GLX_WIDTH
#define GLX_WIDTH 0x801d
#undef GLX_WINDOW
#define GLX_WINDOW 0x8022
#undef GLX_WINDOW_BIT
#define GLX_WINDOW_BIT 0x1
#undef GLX_X_RENDERABLE
#define GLX_X_RENDERABLE 0x8012
#undef GLX_X_VISUAL_TYPE
#define GLX_X_VISUAL_TYPE 0x22

#undef glXChooseFBConfig
#define glXChooseFBConfig _glplatform_glXChooseFBConfig
extern GLXFBConfig * (*glXChooseFBConfig)(Display *, int , const int *, int *);
#undef glXChooseVisual
#define glXChooseVisual _glplatform_glXChooseVisual
extern XVisualInfo * (*glXChooseVisual)(Display *, int , int *);
#undef glXCopyContext
#define glXCopyContext _glplatform_glXCopyContext
extern void (*glXCopyContext)(Display *, GLXContext, GLXContext, unsigned long );
#undef glXCreateContext
#define glXCreateContext _glplatform_glXCreateContext
extern GLXContext (*glXCreateContext)(Display *, XVisualInfo *, GLXContext, Bool);
#undef glXCreateGLXPixmap
#define glXCreateGLXPixmap _glplatform_glXCreateGLXPixmap
extern GLXPixmap (*glXCreateGLXPixmap)(Display *, XVisualInfo *, Pixmap);
#undef glXCreateNewContext
#define glXCreateNewContext _glplatform_glXCreateNewContext
extern GLXContext (*glXCreateNewContext)(Display *, GLXFBConfig, int , GLXContext, Bool);
#undef glXCreatePbuffer
#define glXCreatePbuffer _glplatform_glXCreatePbuffer
extern GLXPbuffer (*glXCreatePbuffer)(Display *, GLXFBConfig, const int *);
#undef glXCreatePixmap
#define glXCreatePixmap _glplatform_glXCreatePixmap
extern GLXPixmap (*glXCreatePixmap)(Display *, GLXFBConfig, Pixmap, const int *);
#undef glXCreateWindow
#define glXCreateWindow _glplatform_glXCreateWindow
extern GLXWindow (*glXCreateWindow)(Display *, GLXFBConfig, Window, const int *);
#undef glXDestroyContext
#define glXDestroyContext _glplatform_glXDestroyContext
extern void (*glXDestroyContext)(Display *, GLXContext);
#undef glXDestroyGLXPixmap
#define glXDestroyGLXPixmap _glplatform_glXDestroyGLXPixmap
extern void (*glXDestroyGLXPixmap)(Display *, GLXPixmap);
#undef glXDestroyPbuffer
#define glXDestroyPbuffer _glplatform_glXDestroyPbuffer
extern void (*glXDestroyPbuffer)(Display *, GLXPbuffer);
#undef glXDestroyPixmap
#define glXDestroyPixmap _glplatform_glXDestroyPixmap
extern void (*glXDestroyPixmap)(Display *, GLXPixmap);
#undef glXDestroyWindow
#define glXDestroyWindow _glplatform_glXDestroyWindow
extern void (*glXDestroyWindow)(Display *, GLXWindow);
#undef glXGetClientString
#define glXGetClientString _glplatform_glXGetClientString
extern const char * (*glXGetClientString)(Display *, int );
#undef glXGetConfig
#define glXGetConfig _glplatform_glXGetConfig
extern int (*glXGetConfig)(Display *, XVisualInfo *, int , int *);
#undef glXGetCurrentContext
#define glXGetCurrentContext _glplatform_glXGetCurrentContext
extern GLXContext (*glXGetCurrentContext)();
#undef glXGetCurrentDisplay
#define glXGetCurrentDisplay _glplatform_glXGetCurrentDisplay
extern Display * (*glXGetCurrentDisplay)();
#undef glXGetCurrentDrawable
#define glXGetCurrentDrawable _glplatform_glXGetCurrentDrawable
extern GLXDrawable (*glXGetCurrentDrawable)();
#undef glXGetCurrentReadDrawable
#define glXGetCurrentReadDrawable _glplatform_glXGetCurrentReadDrawable
extern GLXDrawable (*glXGetCurrentReadDrawable)();
#undef glXGetFBConfigAttrib
#define glXGetFBConfigAttrib _glplatform_glXGetFBConfigAttrib
extern int (*glXGetFBConfigAttrib)(Display *, GLXFBConfig, int , int *);
#undef glXGetFBConfigs
#define glXGetFBConfigs _glplatform_glXGetFBConfigs
extern GLXFBConfig * (*glXGetFBConfigs)(Display *, int , int *);
#undef glXGetProcAddress
#define glXGetProcAddress _glplatform_glXGetProcAddress
extern __GLXextFuncPtr (*glXGetProcAddress)(const GLubyte *);
#undef glXGetSelectedEvent
#define glXGetSelectedEvent _glplatform_glXGetSelectedEvent
extern void (*glXGetSelectedEvent)(Display *, GLXDrawable, unsigned long *);
#undef glXGetVisualFromFBConfig
#define glXGetVisualFromFBConfig _glplatform_glXGetVisualFromFBConfig
extern XVisualInfo * (*glXGetVisualFromFBConfig)(Display *, GLXFBConfig);
#undef glXIsDirect
#define glXIsDirect _glplatform_glXIsDirect
extern Bool (*glXIsDirect)(Display *, GLXContext);
#undef glXMakeContextCurrent
#define glXMakeContextCurrent _glplatform_glXMakeContextCurrent
extern Bool (*glXMakeContextCurrent)(Display *, GLXDrawable, GLXDrawable, GLXContext);
#undef glXMakeCurrent
#define glXMakeCurrent _glplatform_glXMakeCurrent
extern Bool (*glXMakeCurrent)(Display *, GLXDrawable, GLXContext);
#undef glXQueryContext
#define glXQueryContext _glplatform_glXQueryContext
extern int (*glXQueryContext)(Display *, GLXContext, int , int *);
#undef glXQueryDrawable
#define glXQueryDrawable _glplatform_glXQueryDrawable
extern void (*glXQueryDrawable)(Display *, GLXDrawable, int , unsigned int *);
#undef glXQueryExtension
#define glXQueryExtension _glplatform_glXQueryExtension
extern Bool (*glXQueryExtension)(Display *, int *, int *);
#undef glXQueryExtensionsString
#define glXQueryExtensionsString _glplatform_glXQueryExtensionsString
extern const char * (*glXQueryExtensionsString)(Display *, int );
#undef glXQueryServerString
#define glXQueryServerString _glplatform_glXQueryServerString
extern const char * (*glXQueryServerString)(Display *, int , int );
#undef glXQueryVersion
#define glXQueryVersion _glplatform_glXQueryVersion
extern Bool (*glXQueryVersion)(Display *, int *, int *);
#undef glXSelectEvent
#define glXSelectEvent _glplatform_glXSelectEvent
extern void (*glXSelectEvent)(Display *, GLXDrawable, unsigned long );
#undef glXSwapBuffers
#define glXSwapBuffers _glplatform_glXSwapBuffers
extern void (*glXSwapBuffers)(Display *, GLXDrawable);
#undef glXUseXFont
#define glXUseXFont _glplatform_glXUseXFont
extern void (*glXUseXFont)(Font, int , int , int );
#undef glXWaitGL
#define glXWaitGL _glplatform_glXWaitGL
extern void (*glXWaitGL)();
#undef glXWaitX
#define glXWaitX _glplatform_glXWaitX
extern void (*glXWaitX)();


#if defined(GLPLATFORM_ENABLE_GLX_3DFX_multisample)
extern bool GLPLATFORM_GLX_3DFX_multisample;
#undef GLX_SAMPLES_3DFX
#define GLX_SAMPLES_3DFX 0x8051
#undef GLX_SAMPLE_BUFFERS_3DFX
#define GLX_SAMPLE_BUFFERS_3DFX 0x8050

#endif

#if defined(GLPLATFORM_ENABLE_GLX_AMD_gpu_association)
extern bool GLPLATFORM_GLX_AMD_gpu_association;
#undef GLX_GPU_CLOCK_AMD
#define GLX_GPU_CLOCK_AMD 0x21a4
#undef GLX_GPU_FASTEST_TARGET_GPUS_AMD
#define GLX_GPU_FASTEST_TARGET_GPUS_AMD 0x21a2
#undef GLX_GPU_NUM_PIPES_AMD
#define GLX_GPU_NUM_PIPES_AMD 0x21a5
#undef GLX_GPU_NUM_RB_AMD
#define GLX_GPU_NUM_RB_AMD 0x21a7
#undef GLX_GPU_NUM_SIMD_AMD
#define GLX_GPU_NUM_SIMD_AMD 0x21a6
#undef GLX_GPU_NUM_SPI_AMD
#define GLX_GPU_NUM_SPI_AMD 0x21a8
#undef GLX_GPU_OPENGL_VERSION_STRING_AMD
#define GLX_GPU_OPENGL_VERSION_STRING_AMD 0x1f02
#undef GLX_GPU_RAM_AMD
#define GLX_GPU_RAM_AMD 0x21a3
#undef GLX_GPU_RENDERER_STRING_AMD
#define GLX_GPU_RENDERER_STRING_AMD 0x1f01
#undef GLX_GPU_VENDOR_AMD
#define GLX_GPU_VENDOR_AMD 0x1f00

#undef glXBlitContextFramebufferAMD
#define glXBlitContextFramebufferAMD _glplatform_glXBlitContextFramebufferAMD
extern void (*glXBlitContextFramebufferAMD)(GLXContext, GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLbitfield, GLenum);
#undef glXCreateAssociatedContextAMD
#define glXCreateAssociatedContextAMD _glplatform_glXCreateAssociatedContextAMD
extern GLXContext (*glXCreateAssociatedContextAMD)(unsigned int , GLXContext);
#undef glXCreateAssociatedContextAttribsAMD
#define glXCreateAssociatedContextAttribsAMD _glplatform_glXCreateAssociatedContextAttribsAMD
extern GLXContext (*glXCreateAssociatedContextAttribsAMD)(unsigned int , GLXContext, const int *);
#undef glXDeleteAssociatedContextAMD
#define glXDeleteAssociatedContextAMD _glplatform_glXDeleteAssociatedContextAMD
extern Bool (*glXDeleteAssociatedContextAMD)(GLXContext);
#undef glXGetContextGPUIDAMD
#define glXGetContextGPUIDAMD _glplatform_glXGetContextGPUIDAMD
extern unsigned int (*glXGetContextGPUIDAMD)(GLXContext);
#undef glXGetCurrentAssociatedContextAMD
#define glXGetCurrentAssociatedContextAMD _glplatform_glXGetCurrentAssociatedContextAMD
extern GLXContext (*glXGetCurrentAssociatedContextAMD)();
#undef glXGetGPUIDsAMD
#define glXGetGPUIDsAMD _glplatform_glXGetGPUIDsAMD
extern unsigned int (*glXGetGPUIDsAMD)(unsigned int , unsigned int *);
#undef glXGetGPUInfoAMD
#define glXGetGPUInfoAMD _glplatform_glXGetGPUInfoAMD
extern int (*glXGetGPUInfoAMD)(unsigned int , int , GLenum, unsigned int , void *);
#undef glXMakeAssociatedContextCurrentAMD
#define glXMakeAssociatedContextCurrentAMD _glplatform_glXMakeAssociatedContextCurrentAMD
extern Bool (*glXMakeAssociatedContextCurrentAMD)(GLXContext);
#endif

#if defined(GLPLATFORM_ENABLE_GLX_ARB_context_flush_control)
extern bool GLPLATFORM_GLX_ARB_context_flush_control;
#undef GLX_CONTEXT_RELEASE_BEHAVIOR_ARB
#define GLX_CONTEXT_RELEASE_BEHAVIOR_ARB 0x2097
#undef GLX_CONTEXT_RELEASE_BEHAVIOR_FLUSH_ARB
#define GLX_CONTEXT_RELEASE_BEHAVIOR_FLUSH_ARB 0x2098
#undef GLX_CONTEXT_RELEASE_BEHAVIOR_NONE_ARB
#define GLX_CONTEXT_RELEASE_BEHAVIOR_NONE_ARB 0x0

#endif

#if defined(GLPLATFORM_ENABLE_GLX_ARB_create_context)
extern bool GLPLATFORM_GLX_ARB_create_context;
#undef GLX_CONTEXT_DEBUG_BIT_ARB
#define GLX_CONTEXT_DEBUG_BIT_ARB 0x1
#undef GLX_CONTEXT_FLAGS_ARB
#define GLX_CONTEXT_FLAGS_ARB 0x2094
#undef GLX_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB
#define GLX_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB 0x2
#undef GLX_CONTEXT_MAJOR_VERSION_ARB
#define GLX_CONTEXT_MAJOR_VERSION_ARB 0x2091
#undef GLX_CONTEXT_MINOR_VERSION_ARB
#define GLX_CONTEXT_MINOR_VERSION_ARB 0x2092

#undef glXCreateContextAttribsARB
#define glXCreateContextAttribsARB _glplatform_glXCreateContextAttribsARB
extern GLXContext (*glXCreateContextAttribsARB)(Display *, GLXFBConfig, GLXContext, Bool, const int *);
#endif

#if defined(GLPLATFORM_ENABLE_GLX_ARB_create_context_profile)
extern bool GLPLATFORM_GLX_ARB_create_context_profile;
#undef GLX_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB
#define GLX_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB 0x2
#undef GLX_CONTEXT_CORE_PROFILE_BIT_ARB
#define GLX_CONTEXT_CORE_PROFILE_BIT_ARB 0x1
#undef GLX_CONTEXT_PROFILE_MASK_ARB
#define GLX_CONTEXT_PROFILE_MASK_ARB 0x9126

#endif

#if defined(GLPLATFORM_ENABLE_GLX_ARB_create_context_robustness)
extern bool GLPLATFORM_GLX_ARB_create_context_robustness;
#undef GLX_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB
#define GLX_CONTEXT_RESET_NOTIFICATION_STRATEGY_ARB 0x8256
#undef GLX_CONTEXT_ROBUST_ACCESS_BIT_ARB
#define GLX_CONTEXT_ROBUST_ACCESS_BIT_ARB 0x4
#undef GLX_LOSE_CONTEXT_ON_RESET_ARB
#define GLX_LOSE_CONTEXT_ON_RESET_ARB 0x8252
#undef GLX_NO_RESET_NOTIFICATION_ARB
#define GLX_NO_RESET_NOTIFICATION_ARB 0x8261

#endif

#if defined(GLPLATFORM_ENABLE_GLX_ARB_fbconfig_float)
extern bool GLPLATFORM_GLX_ARB_fbconfig_float;
#undef GLX_RGBA_FLOAT_BIT_ARB
#define GLX_RGBA_FLOAT_BIT_ARB 0x4
#undef GLX_RGBA_FLOAT_TYPE_ARB
#define GLX_RGBA_FLOAT_TYPE_ARB 0x20b9

#endif

#if defined(GLPLATFORM_ENABLE_GLX_ARB_framebuffer_sRGB)
extern bool GLPLATFORM_GLX_ARB_framebuffer_sRGB;
#undef GLX_FRAMEBUFFER_SRGB_CAPABLE_ARB
#define GLX_FRAMEBUFFER_SRGB_CAPABLE_ARB 0x20b2

#endif

#if defined(GLPLATFORM_ENABLE_GLX_ARB_get_proc_address)
extern bool GLPLATFORM_GLX_ARB_get_proc_address;
#undef glXGetProcAddressARB
#define glXGetProcAddressARB _glplatform_glXGetProcAddressARB
extern __GLXextFuncPtr (*glXGetProcAddressARB)(const GLubyte *);
#endif

#if defined(GLPLATFORM_ENABLE_GLX_ARB_multisample)
extern bool GLPLATFORM_GLX_ARB_multisample;
#undef GLX_SAMPLES_ARB
#define GLX_SAMPLES_ARB 0x186a1
#undef GLX_SAMPLE_BUFFERS_ARB
#define GLX_SAMPLE_BUFFERS_ARB 0x186a0

#endif

#if defined(GLPLATFORM_ENABLE_GLX_ARB_robustness_application_isolation)
extern bool GLPLATFORM_GLX_ARB_robustness_application_isolation;
#undef GLX_CONTEXT_RESET_ISOLATION_BIT_ARB
#define GLX_CONTEXT_RESET_ISOLATION_BIT_ARB 0x8

#endif

#if defined(GLPLATFORM_ENABLE_GLX_ARB_robustness_share_group_isolation)
extern bool GLPLATFORM_GLX_ARB_robustness_share_group_isolation;
#undef GLX_CONTEXT_RESET_ISOLATION_BIT_ARB
#define GLX_CONTEXT_RESET_ISOLATION_BIT_ARB 0x8

#endif

#if defined(GLPLATFORM_ENABLE_GLX_ARB_vertex_buffer_object)
extern bool GLPLATFORM_GLX_ARB_vertex_buffer_object;
#undef GLX_CONTEXT_ALLOW_BUFFER_BYTE_ORDER_MISMATCH_ARB
#define GLX_CONTEXT_ALLOW_BUFFER_BYTE_ORDER_MISMATCH_ARB 0x2095

#endif

#if defined(GLPLATFORM_ENABLE_GLX_EXT_buffer_age)
extern bool GLPLATFORM_GLX_EXT_buffer_age;
#undef GLX_BACK_BUFFER_AGE_EXT
#define GLX_BACK_BUFFER_AGE_EXT 0x20f4

#endif

#if defined(GLPLATFORM_ENABLE_GLX_EXT_create_context_es2_profile)
extern bool GLPLATFORM_GLX_EXT_create_context_es2_profile;
#undef GLX_CONTEXT_ES2_PROFILE_BIT_EXT
#define GLX_CONTEXT_ES2_PROFILE_BIT_EXT 0x4

#endif

#if defined(GLPLATFORM_ENABLE_GLX_EXT_create_context_es_profile)
extern bool GLPLATFORM_GLX_EXT_create_context_es_profile;
#undef GLX_CONTEXT_ES_PROFILE_BIT_EXT
#define GLX_CONTEXT_ES_PROFILE_BIT_EXT 0x4

#endif

#if defined(GLPLATFORM_ENABLE_GLX_EXT_fbconfig_packed_float)
extern bool GLPLATFORM_GLX_EXT_fbconfig_packed_float;
#undef GLX_RGBA_UNSIGNED_FLOAT_BIT_EXT
#define GLX_RGBA_UNSIGNED_FLOAT_BIT_EXT 0x8
#undef GLX_RGBA_UNSIGNED_FLOAT_TYPE_EXT
#define GLX_RGBA_UNSIGNED_FLOAT_TYPE_EXT 0x20b1

#endif

#if defined(GLPLATFORM_ENABLE_GLX_EXT_framebuffer_sRGB)
extern bool GLPLATFORM_GLX_EXT_framebuffer_sRGB;
#undef GLX_FRAMEBUFFER_SRGB_CAPABLE_EXT
#define GLX_FRAMEBUFFER_SRGB_CAPABLE_EXT 0x20b2

#endif

#if defined(GLPLATFORM_ENABLE_GLX_EXT_import_context)
extern bool GLPLATFORM_GLX_EXT_import_context;
#undef GLX_SCREEN_EXT
#define GLX_SCREEN_EXT 0x800c
#undef GLX_SHARE_CONTEXT_EXT
#define GLX_SHARE_CONTEXT_EXT 0x800a
#undef GLX_VISUAL_ID_EXT
#define GLX_VISUAL_ID_EXT 0x800b

#undef glXFreeContextEXT
#define glXFreeContextEXT _glplatform_glXFreeContextEXT
extern void (*glXFreeContextEXT)(Display *, GLXContext);
#undef glXGetContextIDEXT
#define glXGetContextIDEXT _glplatform_glXGetContextIDEXT
extern GLXContextID (*glXGetContextIDEXT)(const GLXContext);
#undef glXGetCurrentDisplayEXT
#define glXGetCurrentDisplayEXT _glplatform_glXGetCurrentDisplayEXT
extern Display * (*glXGetCurrentDisplayEXT)();
#undef glXImportContextEXT
#define glXImportContextEXT _glplatform_glXImportContextEXT
extern GLXContext (*glXImportContextEXT)(Display *, GLXContextID);
#undef glXQueryContextInfoEXT
#define glXQueryContextInfoEXT _glplatform_glXQueryContextInfoEXT
extern int (*glXQueryContextInfoEXT)(Display *, GLXContext, int , int *);
#endif

#if defined(GLPLATFORM_ENABLE_GLX_EXT_stereo_tree)
extern bool GLPLATFORM_GLX_EXT_stereo_tree;
#undef GLX_STEREO_NOTIFY_EXT
#define GLX_STEREO_NOTIFY_EXT 0x0
#undef GLX_STEREO_NOTIFY_MASK_EXT
#define GLX_STEREO_NOTIFY_MASK_EXT 0x1
#undef GLX_STEREO_TREE_EXT
#define GLX_STEREO_TREE_EXT 0x20f5

#endif

#if defined(GLPLATFORM_ENABLE_GLX_EXT_swap_control)
extern bool GLPLATFORM_GLX_EXT_swap_control;
#undef GLX_MAX_SWAP_INTERVAL_EXT
#define GLX_MAX_SWAP_INTERVAL_EXT 0x20f2
#undef GLX_SWAP_INTERVAL_EXT
#define GLX_SWAP_INTERVAL_EXT 0x20f1

#undef glXSwapIntervalEXT
#define glXSwapIntervalEXT _glplatform_glXSwapIntervalEXT
extern void (*glXSwapIntervalEXT)(Display *, GLXDrawable, int );
#endif

#if defined(GLPLATFORM_ENABLE_GLX_EXT_swap_control_tear)
extern bool GLPLATFORM_GLX_EXT_swap_control_tear;
#undef GLX_LATE_SWAPS_TEAR_EXT
#define GLX_LATE_SWAPS_TEAR_EXT 0x20f3

#endif

#if defined(GLPLATFORM_ENABLE_GLX_EXT_texture_from_pixmap)
extern bool GLPLATFORM_GLX_EXT_texture_from_pixmap;
#undef GLX_AUX0_EXT
#define GLX_AUX0_EXT 0x20e2
#undef GLX_AUX1_EXT
#define GLX_AUX1_EXT 0x20e3
#undef GLX_AUX2_EXT
#define GLX_AUX2_EXT 0x20e4
#undef GLX_AUX3_EXT
#define GLX_AUX3_EXT 0x20e5
#undef GLX_AUX4_EXT
#define GLX_AUX4_EXT 0x20e6
#undef GLX_AUX5_EXT
#define GLX_AUX5_EXT 0x20e7
#undef GLX_AUX6_EXT
#define GLX_AUX6_EXT 0x20e8
#undef GLX_AUX7_EXT
#define GLX_AUX7_EXT 0x20e9
#undef GLX_AUX8_EXT
#define GLX_AUX8_EXT 0x20ea
#undef GLX_AUX9_EXT
#define GLX_AUX9_EXT 0x20eb
#undef GLX_BACK_EXT
#define GLX_BACK_EXT 0x20e0
#undef GLX_BACK_LEFT_EXT
#define GLX_BACK_LEFT_EXT 0x20e0
#undef GLX_BACK_RIGHT_EXT
#define GLX_BACK_RIGHT_EXT 0x20e1
#undef GLX_BIND_TO_MIPMAP_TEXTURE_EXT
#define GLX_BIND_TO_MIPMAP_TEXTURE_EXT 0x20d2
#undef GLX_BIND_TO_TEXTURE_RGBA_EXT
#define GLX_BIND_TO_TEXTURE_RGBA_EXT 0x20d1
#undef GLX_BIND_TO_TEXTURE_RGB_EXT
#define GLX_BIND_TO_TEXTURE_RGB_EXT 0x20d0
#undef GLX_BIND_TO_TEXTURE_TARGETS_EXT
#define GLX_BIND_TO_TEXTURE_TARGETS_EXT 0x20d3
#undef GLX_FRONT_EXT
#define GLX_FRONT_EXT 0x20de
#undef GLX_FRONT_LEFT_EXT
#define GLX_FRONT_LEFT_EXT 0x20de
#undef GLX_FRONT_RIGHT_EXT
#define GLX_FRONT_RIGHT_EXT 0x20df
#undef GLX_MIPMAP_TEXTURE_EXT
#define GLX_MIPMAP_TEXTURE_EXT 0x20d7
#undef GLX_TEXTURE_1D_BIT_EXT
#define GLX_TEXTURE_1D_BIT_EXT 0x1
#undef GLX_TEXTURE_1D_EXT
#define GLX_TEXTURE_1D_EXT 0x20db
#undef GLX_TEXTURE_2D_BIT_EXT
#define GLX_TEXTURE_2D_BIT_EXT 0x2
#undef GLX_TEXTURE_2D_EXT
#define GLX_TEXTURE_2D_EXT 0x20dc
#undef GLX_TEXTURE_FORMAT_EXT
#define GLX_TEXTURE_FORMAT_EXT 0x20d5
#undef GLX_TEXTURE_FORMAT_NONE_EXT
#define GLX_TEXTURE_FORMAT_NONE_EXT 0x20d8
#undef GLX_TEXTURE_FORMAT_RGBA_EXT
#define GLX_TEXTURE_FORMAT_RGBA_EXT 0x20da
#undef GLX_TEXTURE_FORMAT_RGB_EXT
#define GLX_TEXTURE_FORMAT_RGB_EXT 0x20d9
#undef GLX_TEXTURE_RECTANGLE_BIT_EXT
#define GLX_TEXTURE_RECTANGLE_BIT_EXT 0x4
#undef GLX_TEXTURE_RECTANGLE_EXT
#define GLX_TEXTURE_RECTANGLE_EXT 0x20dd
#undef GLX_TEXTURE_TARGET_EXT
#define GLX_TEXTURE_TARGET_EXT 0x20d6
#undef GLX_Y_INVERTED_EXT
#define GLX_Y_INVERTED_EXT 0x20d4

#undef glXBindTexImageEXT
#define glXBindTexImageEXT _glplatform_glXBindTexImageEXT
extern void (*glXBindTexImageEXT)(Display *, GLXDrawable, int , const int *);
#undef glXReleaseTexImageEXT
#define glXReleaseTexImageEXT _glplatform_glXReleaseTexImageEXT
extern void (*glXReleaseTexImageEXT)(Display *, GLXDrawable, int );
#endif

#if defined(GLPLATFORM_ENABLE_GLX_EXT_visual_info)
extern bool GLPLATFORM_GLX_EXT_visual_info;
#undef GLX_DIRECT_COLOR_EXT
#define GLX_DIRECT_COLOR_EXT 0x8003
#undef GLX_GRAY_SCALE_EXT
#define GLX_GRAY_SCALE_EXT 0x8006
#undef GLX_NONE_EXT
#define GLX_NONE_EXT 0x8000
#undef GLX_PSEUDO_COLOR_EXT
#define GLX_PSEUDO_COLOR_EXT 0x8004
#undef GLX_STATIC_COLOR_EXT
#define GLX_STATIC_COLOR_EXT 0x8005
#undef GLX_STATIC_GRAY_EXT
#define GLX_STATIC_GRAY_EXT 0x8007
#undef GLX_TRANSPARENT_ALPHA_VALUE_EXT
#define GLX_TRANSPARENT_ALPHA_VALUE_EXT 0x28
#undef GLX_TRANSPARENT_BLUE_VALUE_EXT
#define GLX_TRANSPARENT_BLUE_VALUE_EXT 0x27
#undef GLX_TRANSPARENT_GREEN_VALUE_EXT
#define GLX_TRANSPARENT_GREEN_VALUE_EXT 0x26
#undef GLX_TRANSPARENT_INDEX_EXT
#define GLX_TRANSPARENT_INDEX_EXT 0x8009
#undef GLX_TRANSPARENT_INDEX_VALUE_EXT
#define GLX_TRANSPARENT_INDEX_VALUE_EXT 0x24
#undef GLX_TRANSPARENT_RED_VALUE_EXT
#define GLX_TRANSPARENT_RED_VALUE_EXT 0x25
#undef GLX_TRANSPARENT_RGB_EXT
#define GLX_TRANSPARENT_RGB_EXT 0x8008
#undef GLX_TRANSPARENT_TYPE_EXT
#define GLX_TRANSPARENT_TYPE_EXT 0x23
#undef GLX_TRUE_COLOR_EXT
#define GLX_TRUE_COLOR_EXT 0x8002
#undef GLX_X_VISUAL_TYPE_EXT
#define GLX_X_VISUAL_TYPE_EXT 0x22

#endif

#if defined(GLPLATFORM_ENABLE_GLX_EXT_visual_rating)
extern bool GLPLATFORM_GLX_EXT_visual_rating;
#undef GLX_NONE_EXT
#define GLX_NONE_EXT 0x8000
#undef GLX_NON_CONFORMANT_VISUAL_EXT
#define GLX_NON_CONFORMANT_VISUAL_EXT 0x800d
#undef GLX_SLOW_VISUAL_EXT
#define GLX_SLOW_VISUAL_EXT 0x8001
#undef GLX_VISUAL_CAVEAT_EXT
#define GLX_VISUAL_CAVEAT_EXT 0x20

#endif

#if defined(GLPLATFORM_ENABLE_GLX_INTEL_swap_event)
extern bool GLPLATFORM_GLX_INTEL_swap_event;
#undef GLX_BUFFER_SWAP_COMPLETE_INTEL_MASK
#define GLX_BUFFER_SWAP_COMPLETE_INTEL_MASK 0x4000000
#undef GLX_COPY_COMPLETE_INTEL
#define GLX_COPY_COMPLETE_INTEL 0x8181
#undef GLX_EXCHANGE_COMPLETE_INTEL
#define GLX_EXCHANGE_COMPLETE_INTEL 0x8180
#undef GLX_FLIP_COMPLETE_INTEL
#define GLX_FLIP_COMPLETE_INTEL 0x8182

#endif

#if defined(GLPLATFORM_ENABLE_GLX_MESA_agp_offset)
extern bool GLPLATFORM_GLX_MESA_agp_offset;
#undef glXGetAGPOffsetMESA
#define glXGetAGPOffsetMESA _glplatform_glXGetAGPOffsetMESA
extern unsigned int (*glXGetAGPOffsetMESA)(const void *);
#endif

#if defined(GLPLATFORM_ENABLE_GLX_MESA_copy_sub_buffer)
extern bool GLPLATFORM_GLX_MESA_copy_sub_buffer;
#undef glXCopySubBufferMESA
#define glXCopySubBufferMESA _glplatform_glXCopySubBufferMESA
extern void (*glXCopySubBufferMESA)(Display *, GLXDrawable, int , int , int , int );
#endif

#if defined(GLPLATFORM_ENABLE_GLX_MESA_pixmap_colormap)
extern bool GLPLATFORM_GLX_MESA_pixmap_colormap;
#undef glXCreateGLXPixmapMESA
#define glXCreateGLXPixmapMESA _glplatform_glXCreateGLXPixmapMESA
extern GLXPixmap (*glXCreateGLXPixmapMESA)(Display *, XVisualInfo *, Pixmap, Colormap);
#endif

#if defined(GLPLATFORM_ENABLE_GLX_MESA_query_renderer)
extern bool GLPLATFORM_GLX_MESA_query_renderer;
#undef GLX_RENDERER_ACCELERATED_MESA
#define GLX_RENDERER_ACCELERATED_MESA 0x8186
#undef GLX_RENDERER_DEVICE_ID_MESA
#define GLX_RENDERER_DEVICE_ID_MESA 0x8184
#undef GLX_RENDERER_ID_MESA
#define GLX_RENDERER_ID_MESA 0x818e
#undef GLX_RENDERER_OPENGL_COMPATIBILITY_PROFILE_VERSION_MESA
#define GLX_RENDERER_OPENGL_COMPATIBILITY_PROFILE_VERSION_MESA 0x818b
#undef GLX_RENDERER_OPENGL_CORE_PROFILE_VERSION_MESA
#define GLX_RENDERER_OPENGL_CORE_PROFILE_VERSION_MESA 0x818a
#undef GLX_RENDERER_OPENGL_ES2_PROFILE_VERSION_MESA
#define GLX_RENDERER_OPENGL_ES2_PROFILE_VERSION_MESA 0x818d
#undef GLX_RENDERER_OPENGL_ES_PROFILE_VERSION_MESA
#define GLX_RENDERER_OPENGL_ES_PROFILE_VERSION_MESA 0x818c
#undef GLX_RENDERER_PREFERRED_PROFILE_MESA
#define GLX_RENDERER_PREFERRED_PROFILE_MESA 0x8189
#undef GLX_RENDERER_UNIFIED_MEMORY_ARCHITECTURE_MESA
#define GLX_RENDERER_UNIFIED_MEMORY_ARCHITECTURE_MESA 0x8188
#undef GLX_RENDERER_VENDOR_ID_MESA
#define GLX_RENDERER_VENDOR_ID_MESA 0x8183
#undef GLX_RENDERER_VERSION_MESA
#define GLX_RENDERER_VERSION_MESA 0x8185
#undef GLX_RENDERER_VIDEO_MEMORY_MESA
#define GLX_RENDERER_VIDEO_MEMORY_MESA 0x8187

#undef glXQueryCurrentRendererIntegerMESA
#define glXQueryCurrentRendererIntegerMESA _glplatform_glXQueryCurrentRendererIntegerMESA
extern Bool (*glXQueryCurrentRendererIntegerMESA)(int , unsigned int *);
#undef glXQueryCurrentRendererStringMESA
#define glXQueryCurrentRendererStringMESA _glplatform_glXQueryCurrentRendererStringMESA
extern const char * (*glXQueryCurrentRendererStringMESA)(int );
#undef glXQueryRendererIntegerMESA
#define glXQueryRendererIntegerMESA _glplatform_glXQueryRendererIntegerMESA
extern Bool (*glXQueryRendererIntegerMESA)(Display *, int , int , int , unsigned int *);
#undef glXQueryRendererStringMESA
#define glXQueryRendererStringMESA _glplatform_glXQueryRendererStringMESA
extern const char * (*glXQueryRendererStringMESA)(Display *, int , int , int );
#endif

#if defined(GLPLATFORM_ENABLE_GLX_MESA_release_buffers)
extern bool GLPLATFORM_GLX_MESA_release_buffers;
#undef glXReleaseBuffersMESA
#define glXReleaseBuffersMESA _glplatform_glXReleaseBuffersMESA
extern Bool (*glXReleaseBuffersMESA)(Display *, GLXDrawable);
#endif

#if defined(GLPLATFORM_ENABLE_GLX_MESA_set_3dfx_mode)
extern bool GLPLATFORM_GLX_MESA_set_3dfx_mode;
#undef GLX_3DFX_FULLSCREEN_MODE_MESA
#define GLX_3DFX_FULLSCREEN_MODE_MESA 0x2
#undef GLX_3DFX_WINDOW_MODE_MESA
#define GLX_3DFX_WINDOW_MODE_MESA 0x1

#undef glXSet3DfxModeMESA
#define glXSet3DfxModeMESA _glplatform_glXSet3DfxModeMESA
extern Bool (*glXSet3DfxModeMESA)(int );
#endif

#if defined(GLPLATFORM_ENABLE_GLX_NV_copy_buffer)
extern bool GLPLATFORM_GLX_NV_copy_buffer;
#undef glXCopyBufferSubDataNV
#define glXCopyBufferSubDataNV _glplatform_glXCopyBufferSubDataNV
extern void (*glXCopyBufferSubDataNV)(Display *, GLXContext, GLXContext, GLenum, GLenum, GLintptr, GLintptr, GLsizeiptr);
#undef glXNamedCopyBufferSubDataNV
#define glXNamedCopyBufferSubDataNV _glplatform_glXNamedCopyBufferSubDataNV
extern void (*glXNamedCopyBufferSubDataNV)(Display *, GLXContext, GLXContext, GLuint, GLuint, GLintptr, GLintptr, GLsizeiptr);
#endif

#if defined(GLPLATFORM_ENABLE_GLX_NV_copy_image)
extern bool GLPLATFORM_GLX_NV_copy_image;
#undef glXCopyImageSubDataNV
#define glXCopyImageSubDataNV _glplatform_glXCopyImageSubDataNV
extern void (*glXCopyImageSubDataNV)(Display *, GLXContext, GLuint, GLenum, GLint, GLint, GLint, GLint, GLXContext, GLuint, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei);
#endif

#if defined(GLPLATFORM_ENABLE_GLX_NV_delay_before_swap)
extern bool GLPLATFORM_GLX_NV_delay_before_swap;
#undef glXDelayBeforeSwapNV
#define glXDelayBeforeSwapNV _glplatform_glXDelayBeforeSwapNV
extern Bool (*glXDelayBeforeSwapNV)(Display *, GLXDrawable, GLfloat);
#endif

#if defined(GLPLATFORM_ENABLE_GLX_NV_float_buffer)
extern bool GLPLATFORM_GLX_NV_float_buffer;
#undef GLX_FLOAT_COMPONENTS_NV
#define GLX_FLOAT_COMPONENTS_NV 0x20b0

#endif

#if defined(GLPLATFORM_ENABLE_GLX_NV_multisample_coverage)
extern bool GLPLATFORM_GLX_NV_multisample_coverage;
#undef GLX_COLOR_SAMPLES_NV
#define GLX_COLOR_SAMPLES_NV 0x20b3
#undef GLX_COVERAGE_SAMPLES_NV
#define GLX_COVERAGE_SAMPLES_NV 0x186a1

#endif

#if defined(GLPLATFORM_ENABLE_GLX_NV_present_video)
extern bool GLPLATFORM_GLX_NV_present_video;
#undef GLX_NUM_VIDEO_SLOTS_NV
#define GLX_NUM_VIDEO_SLOTS_NV 0x20f0

#undef glXBindVideoDeviceNV
#define glXBindVideoDeviceNV _glplatform_glXBindVideoDeviceNV
extern int (*glXBindVideoDeviceNV)(Display *, unsigned int , unsigned int , const int *);
#undef glXEnumerateVideoDevicesNV
#define glXEnumerateVideoDevicesNV _glplatform_glXEnumerateVideoDevicesNV
extern unsigned int * (*glXEnumerateVideoDevicesNV)(Display *, int , int *);
#endif

#if defined(GLPLATFORM_ENABLE_GLX_NV_swap_group)
extern bool GLPLATFORM_GLX_NV_swap_group;
#undef glXBindSwapBarrierNV
#define glXBindSwapBarrierNV _glplatform_glXBindSwapBarrierNV
extern Bool (*glXBindSwapBarrierNV)(Display *, GLuint, GLuint);
#undef glXJoinSwapGroupNV
#define glXJoinSwapGroupNV _glplatform_glXJoinSwapGroupNV
extern Bool (*glXJoinSwapGroupNV)(Display *, GLXDrawable, GLuint);
#undef glXQueryFrameCountNV
#define glXQueryFrameCountNV _glplatform_glXQueryFrameCountNV
extern Bool (*glXQueryFrameCountNV)(Display *, int , GLuint *);
#undef glXQueryMaxSwapGroupsNV
#define glXQueryMaxSwapGroupsNV _glplatform_glXQueryMaxSwapGroupsNV
extern Bool (*glXQueryMaxSwapGroupsNV)(Display *, int , GLuint *, GLuint *);
#undef glXQuerySwapGroupNV
#define glXQuerySwapGroupNV _glplatform_glXQuerySwapGroupNV
extern Bool (*glXQuerySwapGroupNV)(Display *, GLXDrawable, GLuint *, GLuint *);
#undef glXResetFrameCountNV
#define glXResetFrameCountNV _glplatform_glXResetFrameCountNV
extern Bool (*glXResetFrameCountNV)(Display *, int );
#endif

#if defined(GLPLATFORM_ENABLE_GLX_NV_video_capture)
extern bool GLPLATFORM_GLX_NV_video_capture;
#undef GLX_DEVICE_ID_NV
#define GLX_DEVICE_ID_NV 0x20cd
#undef GLX_NUM_VIDEO_CAPTURE_SLOTS_NV
#define GLX_NUM_VIDEO_CAPTURE_SLOTS_NV 0x20cf
#undef GLX_UNIQUE_ID_NV
#define GLX_UNIQUE_ID_NV 0x20ce

#undef glXBindVideoCaptureDeviceNV
#define glXBindVideoCaptureDeviceNV _glplatform_glXBindVideoCaptureDeviceNV
extern int (*glXBindVideoCaptureDeviceNV)(Display *, unsigned int , GLXVideoCaptureDeviceNV);
#undef glXEnumerateVideoCaptureDevicesNV
#define glXEnumerateVideoCaptureDevicesNV _glplatform_glXEnumerateVideoCaptureDevicesNV
extern GLXVideoCaptureDeviceNV * (*glXEnumerateVideoCaptureDevicesNV)(Display *, int , int *);
#undef glXLockVideoCaptureDeviceNV
#define glXLockVideoCaptureDeviceNV _glplatform_glXLockVideoCaptureDeviceNV
extern void (*glXLockVideoCaptureDeviceNV)(Display *, GLXVideoCaptureDeviceNV);
#undef glXQueryVideoCaptureDeviceNV
#define glXQueryVideoCaptureDeviceNV _glplatform_glXQueryVideoCaptureDeviceNV
extern int (*glXQueryVideoCaptureDeviceNV)(Display *, GLXVideoCaptureDeviceNV, int , int *);
#undef glXReleaseVideoCaptureDeviceNV
#define glXReleaseVideoCaptureDeviceNV _glplatform_glXReleaseVideoCaptureDeviceNV
extern void (*glXReleaseVideoCaptureDeviceNV)(Display *, GLXVideoCaptureDeviceNV);
#endif

#if defined(GLPLATFORM_ENABLE_GLX_NV_video_out)
extern bool GLPLATFORM_GLX_NV_video_out;
#undef GLX_VIDEO_OUT_ALPHA_NV
#define GLX_VIDEO_OUT_ALPHA_NV 0x20c4
#undef GLX_VIDEO_OUT_COLOR_AND_ALPHA_NV
#define GLX_VIDEO_OUT_COLOR_AND_ALPHA_NV 0x20c6
#undef GLX_VIDEO_OUT_COLOR_AND_DEPTH_NV
#define GLX_VIDEO_OUT_COLOR_AND_DEPTH_NV 0x20c7
#undef GLX_VIDEO_OUT_COLOR_NV
#define GLX_VIDEO_OUT_COLOR_NV 0x20c3
#undef GLX_VIDEO_OUT_DEPTH_NV
#define GLX_VIDEO_OUT_DEPTH_NV 0x20c5
#undef GLX_VIDEO_OUT_FIELD_1_NV
#define GLX_VIDEO_OUT_FIELD_1_NV 0x20c9
#undef GLX_VIDEO_OUT_FIELD_2_NV
#define GLX_VIDEO_OUT_FIELD_2_NV 0x20ca
#undef GLX_VIDEO_OUT_FRAME_NV
#define GLX_VIDEO_OUT_FRAME_NV 0x20c8
#undef GLX_VIDEO_OUT_STACKED_FIELDS_1_2_NV
#define GLX_VIDEO_OUT_STACKED_FIELDS_1_2_NV 0x20cb
#undef GLX_VIDEO_OUT_STACKED_FIELDS_2_1_NV
#define GLX_VIDEO_OUT_STACKED_FIELDS_2_1_NV 0x20cc

#undef glXBindVideoImageNV
#define glXBindVideoImageNV _glplatform_glXBindVideoImageNV
extern int (*glXBindVideoImageNV)(Display *, GLXVideoDeviceNV, GLXPbuffer, int );
#undef glXGetVideoDeviceNV
#define glXGetVideoDeviceNV _glplatform_glXGetVideoDeviceNV
extern int (*glXGetVideoDeviceNV)(Display *, int , int , GLXVideoDeviceNV *);
#undef glXGetVideoInfoNV
#define glXGetVideoInfoNV _glplatform_glXGetVideoInfoNV
extern int (*glXGetVideoInfoNV)(Display *, int , GLXVideoDeviceNV, unsigned long *, unsigned long *);
#undef glXReleaseVideoDeviceNV
#define glXReleaseVideoDeviceNV _glplatform_glXReleaseVideoDeviceNV
extern int (*glXReleaseVideoDeviceNV)(Display *, int , GLXVideoDeviceNV);
#undef glXReleaseVideoImageNV
#define glXReleaseVideoImageNV _glplatform_glXReleaseVideoImageNV
extern int (*glXReleaseVideoImageNV)(Display *, GLXPbuffer);
#undef glXSendPbufferToVideoNV
#define glXSendPbufferToVideoNV _glplatform_glXSendPbufferToVideoNV
extern int (*glXSendPbufferToVideoNV)(Display *, GLXPbuffer, int , unsigned long *, GLboolean);
#endif

#if defined(GLPLATFORM_ENABLE_GLX_OML_swap_method)
extern bool GLPLATFORM_GLX_OML_swap_method;
#undef GLX_SWAP_COPY_OML
#define GLX_SWAP_COPY_OML 0x8062
#undef GLX_SWAP_EXCHANGE_OML
#define GLX_SWAP_EXCHANGE_OML 0x8061
#undef GLX_SWAP_METHOD_OML
#define GLX_SWAP_METHOD_OML 0x8060
#undef GLX_SWAP_UNDEFINED_OML
#define GLX_SWAP_UNDEFINED_OML 0x8063

#endif

#if defined(GLPLATFORM_ENABLE_GLX_OML_sync_control)
extern bool GLPLATFORM_GLX_OML_sync_control;
#undef glXGetMscRateOML
#define glXGetMscRateOML _glplatform_glXGetMscRateOML
extern Bool (*glXGetMscRateOML)(Display *, GLXDrawable, int32_t *, int32_t *);
#undef glXGetSyncValuesOML
#define glXGetSyncValuesOML _glplatform_glXGetSyncValuesOML
extern Bool (*glXGetSyncValuesOML)(Display *, GLXDrawable, int64_t *, int64_t *, int64_t *);
#undef glXSwapBuffersMscOML
#define glXSwapBuffersMscOML _glplatform_glXSwapBuffersMscOML
extern int64_t (*glXSwapBuffersMscOML)(Display *, GLXDrawable, int64_t, int64_t, int64_t);
#undef glXWaitForMscOML
#define glXWaitForMscOML _glplatform_glXWaitForMscOML
extern Bool (*glXWaitForMscOML)(Display *, GLXDrawable, int64_t, int64_t, int64_t, int64_t *, int64_t *, int64_t *);
#undef glXWaitForSbcOML
#define glXWaitForSbcOML _glplatform_glXWaitForSbcOML
extern Bool (*glXWaitForSbcOML)(Display *, GLXDrawable, int64_t, int64_t *, int64_t *, int64_t *);
#endif

#if defined(GLPLATFORM_ENABLE_GLX_SGI_swap_control)
extern bool GLPLATFORM_GLX_SGI_swap_control;
#undef glXSwapIntervalSGI
#define glXSwapIntervalSGI _glplatform_glXSwapIntervalSGI
extern int (*glXSwapIntervalSGI)(int );
#endif

#if defined(GLPLATFORM_ENABLE_GLX_SUN_get_transparent_index)
extern bool GLPLATFORM_GLX_SUN_get_transparent_index;
#undef glXGetTransparentIndexSUN
#define glXGetTransparentIndexSUN _glplatform_glXGetTransparentIndexSUN
extern Status (*glXGetTransparentIndexSUN)(Display *, Window, Window, long *);
#endif

bool glplatform_glx_init(int maj, int min);

#ifdef __cplusplus
}
#endif
#endif
